Wed, 06 Jun 2018 10:38:50 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:50 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:50 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:50 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:50 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:50 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:50 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:50 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:50 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:51 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Wed, 06 Jun 2018 10:38:52 app_thread.py[line:232] ERROR 识别价格失败
Wed, 06 Jun 2018 10:38:52 app_thread.py[line:233] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 526, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Wed, 06 Jun 2018 10:38:52 app_thread.py[line:232] ERROR 识别价格失败
Wed, 06 Jun 2018 10:38:52 app_thread.py[line:233] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 526, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Wed, 06 Jun 2018 10:38:52 app_thread.py[line:232] ERROR 识别价格失败
Wed, 06 Jun 2018 10:38:52 app_thread.py[line:233] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 526, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Wed, 06 Jun 2018 10:38:52 app_thread.py[line:232] ERROR 识别价格失败
Wed, 06 Jun 2018 10:38:52 app_thread.py[line:233] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 526, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Wed, 06 Jun 2018 10:38:52 app_thread.py[line:232] ERROR 识别价格失败
Wed, 06 Jun 2018 10:38:52 app_thread.py[line:233] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 526, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:52 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Wed, 06 Jun 2018 10:38:52 app_thread.py[line:232] ERROR 识别价格失败
Wed, 06 Jun 2018 10:38:52 app_thread.py[line:233] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 526, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Wed, 06 Jun 2018 10:38:53 app_thread.py[line:232] ERROR 识别价格失败
Wed, 06 Jun 2018 10:38:53 app_thread.py[line:233] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 526, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Wed, 06 Jun 2018 10:38:53 app_thread.py[line:232] ERROR 识别价格失败
Wed, 06 Jun 2018 10:38:53 app_thread.py[line:233] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 526, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Wed, 06 Jun 2018 10:38:53 app_thread.py[line:232] ERROR 识别价格失败
Wed, 06 Jun 2018 10:38:53 app_thread.py[line:233] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 526, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:222] ERROR error message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 166, in cut
    diff = xy[-1][2]  # 最后一个 图像块
IndexError: list index out of range
Wed, 06 Jun 2018 10:38:53 app_thread.py[line:232] ERROR 识别价格失败
Wed, 06 Jun 2018 10:38:53 app_thread.py[line:233] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 212, in run
    str_price = Price_read()
  File "E:\hupai\component\imgcut.py", line 526, in Price_read
    price = readpic(lowest_price_img, 'maindata.xml')
  File "E:\hupai\component\imgcut.py", line 231, in readpic
    result = result[1].reshape(-1).astype(int).astype(str)
AttributeError: 'NoneType' object has no attribute 'reshape'
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:53 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:54 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:447] INFO 截图成功
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:449] INFO imgpos_yanzhengma 43:153, 358:538
Wed, 06 Jun 2018 10:38:55 imgcut.py[line:451] INFO imgpos_yanzhengmaconfirm 118:218, 175:535
