Thu, 29 Mar 2018 21:34:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:34:13 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:13 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 65536
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:13 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:13 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:13 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:13 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:13 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:13 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:13 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:13 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:13 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:13 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:13 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:13 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:13 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:13 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:13 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:13 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:13 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:13 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:14 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:14 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:14 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:14 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:14 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:14 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:14 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:14 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:14 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:14 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:14 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:14 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:14 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:14 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:14 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:14 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:14 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:14 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:14 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:14 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:15 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:15 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:15 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:15 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:15 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:15 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:15 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:15 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:15 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:15 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:15 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:15 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:15 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:15 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:15 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:15 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:15 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:15 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:15 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:15 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:15 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:16 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:16 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:16 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:16 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:16 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:16 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:16 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:16 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:16 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:16 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:16 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:16 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:16 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:16 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:16 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:16 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:16 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:16 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:16 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:16 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:16 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:16 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:17 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:17 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:17 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:17 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:17 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:17 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:17 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:17 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:17 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:17 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:17 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:17 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:17 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:17 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:17 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:17 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:17 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:17 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:17 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:18 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:18 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:18 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:18 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:18 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:18 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:18 imgcut.py[line:309] ERROR cut_img 这里出错
Thu, 29 Mar 2018 21:34:18 imgcut.py[line:310] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\imgcut.py", line 302, in cut_img
    set_val('imgpos_lowestprice', img[use_area[0][1]:use_area[0][3], use_area[0][0]:use_area[0][2]])  # ok
IndexError: list index out of range
Thu, 29 Mar 2018 21:34:18 app_thread.py[line:125] ERROR 刷新失败
Thu, 29 Mar 2018 21:34:18 app_thread.py[line:126] ERROR this is an exception message
Traceback (most recent call last):
  File "E:\hupai\component\app_thread.py", line 123, in run
    findrefresh()
  File "E:\hupai\component\imgcut.py", line 324, in findrefresh
    img = cv2.cvtColor(sc, cv2.COLOR_BGR2GRAY)  # 转灰度图
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:11073: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cv::cvtColor

Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:40 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:41 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:42 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:42 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:42 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:42 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:42 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:42 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:44 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:44 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:44 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:44 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:44 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:44 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:44 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:44 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:45 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:46 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:34:51 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:51 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:51 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:51 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:34:51 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:51 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:34:51 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:51 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:52 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:53 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:54 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:34:55 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:06 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:07 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:08 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:09 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:09 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:09 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:09 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:09 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:09 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:09 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:09 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:10 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:11 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:12 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 985
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:16 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:17 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:18 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:19 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:20 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:20 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:20 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:20 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:20 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:20 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:20 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:20 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
Thu, 29 Mar 2018 21:35:20 PngImagePlugin.py[line:137] DEBUG STREAM b'IHDR' 16 13
Thu, 29 Mar 2018 21:35:20 PngImagePlugin.py[line:137] DEBUG STREAM b'IDAT' 41 8192
